usniffer = {
	'demo' : [
		'inc/*',
		'inc/boards',
		'vendor//*',
		'uracoli/*',
		'*',
	],
	'emb6' : [
		'ipv6',
		'sicslowpan',
		'llsec',
		'nullmac',
		'sniffer',
	],
	'utils' : [
		'*',
	],
# C global defines
	'defines' : [
		('DEMO_USE_USNIFFER',1),
		('UIP_CONF_ND6_SEND_RA',0),
		('UIP_CONF_ND6_SEND_NA',0),
	],
# GCC flags
	'cflags' : [
	]	
}

Return('usniffer')