/* Copyright (c) 2007 Axel Wachtler
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

   * Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in the
     documentation and/or other materials provided with the distribution.
   * Neither the name of the authors nor the names of its contributors
     may be used to endorse or promote products derived from this software
     without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
   POSSIBILITY OF SUCH DAMAGE. */

/* $Id$ */
/**
 * @file
 * @brief Interface for @ref grpTrx.
 * @ingroup grpTrx
 */
#ifndef TRANSCEIVER_H
#define TRANSCEIVER_H

/**
 *  @addtogroup grpTrx
 *  @{
 */

/* === Includes ============================================================== */
#include "board.h"

#if RADIO_TYPE == RADIO_AT86RF230 || defined(DOXYGEN)
# include "at86rf230a.h"
#elif RADIO_TYPE == RADIO_AT86RF230B
# include "at86rf230b.h"
#elif RADIO_TYPE == RADIO_AT86RF231
# include "at86rf231.h"
#elif RADIO_TYPE == RADIO_AT86RF212
# include "at86rf212.h"
#elif RADIO_TYPE == RADIO_AT86RF232
# include "at86rf232.h"
#elif RADIO_TYPE == RADIO_AT86RF233
# include "at86rf233.h"
#elif RADIO_TYPE == RADIO_ATMEGA128RFA1_A ||\
      RADIO_TYPE == RADIO_ATMEGA128RFA1_B ||\
      RADIO_TYPE == RADIO_ATMEGA128RFA1_C ||\
      RADIO_TYPE == RADIO_ATMEGA128RFA1_D
# include "atmega_rfa1.h"
#elif RADIO_TYPE == RADIO_ATMEGA256RFR2
# include "atmega_rfr2.h"
#else
# error "RADIO_TYPE is not defined or wrong"
#endif
#include <stdbool.h>

/* === Externals ============================================================= */

/* === Types ================================================================= */

/* Data Rate macros, generated by python Tools/cmdhash.py  `cat rates.txt` */
#define BPSK20 (0x52)
#define BPSK20_STR "BPSK20"
#define BPSK40 (0x92)
#define BPSK40_STR "BPSK40"
#define OQPSK100 (0x90)
#define OQPSK100_STR "OQPSK100"
#define OQPSK200 (0x93)
#define OQPSK200_STR "OQPSK200"
#define OQPSK250 (0x33)
#define OQPSK250_STR "OQPSK250"
#define OQPSK400 (0x95)
#define OQPSK400_STR "OQPSK400"
#define OQPSK500 (0x94)
#define OQPSK500_STR "OQPSK500"
#define OQPSK1000 (0x34)
#define OQPSK1000_STR "OQPSK1000"
#define OQPSK2000 (0x54)
#define OQPSK2000_STR "OQPSK2000"

#define RATE_NONE (0xFF)

/** Maximum size in bytes of an IEEE 802.15.4 frame */
#ifndef MAX_FRAME_SIZE
# define MAX_FRAME_SIZE (127)
#endif

/* channel handling */
#define TRX_NEXT_CHANNEL(x) ((channel_t)(x+1) > TRX_MAX_CHANNEL ? TRX_MAX_CHANNEL : x+1)
#define TRX_PREV_CHANNEL(x) ((channel_t)(x-1) < TRX_MIN_CHANNEL ? TRX_MIN_CHANNEL : x-1)
#define TRX_NEXT_CHANNEL_WRAP(x) ((channel_t)(x+1) > TRX_MAX_CHANNEL ? TRX_MIN_CHANNEL : x+1 )
#define TRX_PREV_CHANNEL_WRAP(x) ((channel_t)(x-1) < TRX_MIN_CHANNEL ? TRX_MAX_CHANNEL : x-1 )

#ifndef DEFAULT_SPI_RATE
/* define a dummy SPI RATE */
# define DEFAULT_SPI_RATE  (0)
#endif


/**
 *  @}
 */
#endif /* TRANSCEIVER_H */
